### ISSUE TITLE
Should JavaScript files be included in the replace array?

### ISSUE THREAD

**Issue by josiahsprague** [SparkartGroupInc/broadway#11]
Opening this issue based on @joanniclaborde's comment here: https://github.com/SparkartGroupInc/jungle-solidus-template/pull/1#discussion_r23843951

Re: [fingerprint task](https://github.com/SparkartGroupInc/broadway/blob/master/tasks/fingerprint.js)

> do you think javascript files should be included in the replace array? For browserified templates that reference js files?

**Comment by josiahsprague** [comment]
@joanniclaborde Do you have an example of browserified templates that reference js files?

**Comment by joanniclaborde** [comment]
I guess it's more likely that JS files will reference images. Here's a file @pushred deployed last night: https://github.com/SparkartGroupInc/keithurban.net/blob/fix-event-times/assets/scripts/featured-slideshow.js#L31

**Comment by josiahsprague** [comment]
Staged a PR for this. Should be ready to merge as soon as someone gives a thumbs up.
